server.servlet.context-path=/spring_crud
server.port=7779
spring.thymeleaf.cache=false

#PostgresDB\u63a5\u7d9a \u672c\u756a\u74b0\u5883
#AWS\u63a5\u7d9a\u6642
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://ex1-db1.cn2myy0yi1o4.ap-northeast-1.rds.amazonaws.com:5432/rp3db
spring.datasource.username=spring_training_user
spring.datasource.password=systemsss

spring.mvc.format.date=yyyy/MM/dd

#MyBatis\u306e\u8a2d\u5b9a
mybatis.configuration.map-underscore-to-camel-case=true
